# http://localhost:8080/graphiql?path=/graphql

### Get employee by id
POST http://localhost:8080/graphql
Content-Type: application/json

{
  "query": "query MyQuery { getEmployee(id: \"10\") { id name location { city createDate id name } } }"
}

POST http://localhost:8080/graphql
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="operations"

{
  "query": "mutation($file: Upload!) { uploadFile(file: $file) }",
  "variables": { "file": null }
}

