# http://localhost:8080/graphiql?path=/graphql

### Get employee by id
POST http://localhost:8080/graphql
Content-Type: application/json

{
  "query": "query Test { getEmployee(id: \"10\") { id name location { city createDate id name dueDate } } }"
}

POST http://localhost:8080/graphql
Content-Type: application/json

{
  "query": "query Test($id: ID!) { getEmployee(id: $id) { id name location { city createDate id name dueDate } } }",
  "variables": {
    "id": "10"
  }
}

curl --request POST \
  --url http://localhost:8080/graphql \
  --header 'Content-Type: application/json' \
  --header 'User-Agent: vscode-restclient' \
  --data '{
    "query": "query Test($id: ID!) { getEmployee(id: $id) { id name location { city createDate id name dueDate } } }",
    "variables": {"id": "10"}
  }'


### Get task
POST http://localhost:8080/graphql
Content-Type: application/json

{
  "query": "query TaskFilterInput($filter: TaskFilterInput!) { getTasksByFilter(filter: $filter) { id title description priority status dueDate createDate } }",
  "variables": {
    "filter": {
      "priority": null,
      "status": null,
      "dueDateBefore": null
    }
  }
}


### Create Task
POST http://localhost:8080/graphql
Content-Type: application/json

{
  "query": "mutation CreateTask($input: CreateTaskDto!) { createTask(input: $input) { id title description priority status dueDate createDate } }",
  "variables": {
    "input": {
      "title": "Finish project",
      "description": "Complete GraphQL implementation using records",
      "priority": "HIGH",
      "dueDate": "2026-02-19"
    }
  }
}

### Update Task
POST http://localhost:8080/graphql
Content-Type: application/json

{
  "query": "mutation UpdateTask($input: UpdateTaskDto!) { updateTask(input: $input) { id title description priority status dueDate createDate } }",
  "variables": {
    "input": {
      "id": "26ac40da-4634-4455-a2a1-5b6330c41cea",
      "title": "Finish project 2",
      "description": "2 Complete GraphQL implementation using records",
      "priority": "LOW",
      "dueDate": "2021-02-19"
    }
  }
}

### Delete Task
POST http://localhost:8080/graphql
Content-Type: application/json

{
  "query": "mutation DeleteTask($id: String!) { deleteTaskById(id: $id) }",
  "variables": {
    "id": "26ac40da-4634-4455-a2a1-5b6330c41cea"
  }
}

### Rest tests:

### Get task
GET http://localhost:8080/tasks
Content-Type: application/json


GET http://localhost:8080/tasks?priority=NONE&status=CREATED&dueDateBefore=2033-12-25
Content-Type: application/json


### Create Task
POST http://localhost:8080/tasks
Content-Type: application/json

{
  "title": "Finish project",
  "description": "Complete GraphQL implementation using records",
  "priority": "HIGH",
  "dueDate": "2026-02-19"
}

### Update Task
PUT http://localhost:8080/tasks/1
Content-Type: application/json

{
  "id": "26ac40da-4634-4455-a2a1-5b6330c41cea",
  "title": "Finish project 2",
  "description": "2 Complete GraphQL implementation using records",
  "priority": "LOW",
  "dueDate": "2021-02-19"
}

### Delete Task
DELETE http://localhost:8080/tasks/1
Content-Type: application/json
